### ISSUE TITLE
building stylus with makefile

### ISSUE THREAD

**Issue by hallas** [deedubs/component-stylus#6]
Hi.

Do you know how I can achieve building a stylus component with a makefile?

**Comment by lvivier** [comment]
If you're building a component using `component(1)` and you need a plugin, try the `--use` or `-u` option:

```
$ component build --use component-stylus
```

**Comment by deedubs** [comment]
Adding something like 

```
build:
  @component build --use component-stylus 
```

should do the trick

**Comment by hallas** [comment]
ended up with my own component builder, adding component-stylus with .use, it's perfect

**Comment by deedubs** [comment]
Nice! Yeah we use https://github.com/deedubs/build for bending component to our will
